# Generated by Django 6.0.7 on 2026-08-12 08:54

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='telegram_message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
