# Generated by Django 6.0.7 on 2026-08-12 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_managers_product_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_funnels', to=settings.AUTH_USER_MODEL),
        ),
    ]
