# Generated by Django 6.0.7 on 2026-08-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_funnel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('packing', 'Qadoqlash'), ('later', 'Keyin oladi'), ('returned', 'Qaytib keldi'), ('cancelled', 'Bekor qilindi'), ('hold', 'Hold'), ('archive', 'Arxiv'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi')], default='new', max_length=20),
        ),
    ]
