# Generated by Django 6.0.7 on 2026-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_order_district_order_operator_order_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Ushbu oqim orqali yetkazib berilgan har bir dona uchun sotuvchiga to'lanadigan komissiya", max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restocked',
            field=models.BooleanField(default=False),
        ),
    ]
